### ISSUE TITLE
Wrong command doesn't get processed

### ISSUE THREAD

**Issue by pPris** [AY2021S2-CS2103T-T11-4/tp#186]
`add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01 d/13-05-2021 o/2 x Strawberry Cake : Adds a 2 x Strawberry Cake`

this command doesn't get processed, like there's no change in the command output or anything indicating an error. Note the colon in the input.

weeeirddd rare bug I think.

**Comment by simran-bhadani3** [comment]
I think this might be happening because of the regex that I set for order items so probably it isn't able to convert the order description to an order item. Will try to allow the regex to accept special characters as well and see if it works.
