### ISSUE TITLE
"Index is not a non-zero unsigned integer." may be too technical of an error message

### ISSUE THREAD

**Issue by pPris** [AY2021S2-CS2103T-T11-4/tp#189]
I think there was a PE-D bug that reported this error message but I can't find it anymore

Same if `-1111` was used.

Quoting the part that was wrong might make this err msg more helpful too.

![image](https://user-images.githubusercontent.com/49683462/113516288-fe1a1300-95ab-11eb-9980-9d6bd9b63c7b.png)

**Comment by simran-bhadani3** [comment]
Linked to #165
